### 2024-04-16 Probability

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.normal(size = 10)

array([-2.04214991,  0.08113256, -1.87107114, -0.82344947, -0.08280719,
       -1.29072007,  0.35241581,  0.76473137, -0.17989931,  0.63714633])

In [3]:
np.random.normal(size = (4,3))

array([[ 0.33511681,  0.43350747,  1.43706252],
       [-1.1261218 ,  1.60026788,  1.11068582],
       [ 1.6766896 ,  1.161208  ,  0.04508046],
       [-0.09616393,  1.83948878,  0.43135906]])

In [4]:
np.random.choice(6, size = 10)

array([3, 0, 3, 2, 3, 3, 4, 5, 1, 4])

In [5]:
1 + np.random.choice(6, size = 10)

array([2, 5, 3, 4, 5, 3, 2, 2, 4, 4])

In [6]:
np.random.seed(7)
1 + np.random.choice(6, size = 10)

array([5, 2, 4, 4, 5, 2, 1, 2, 3, 3])

In [7]:
d = 1 + np.random.choice(6, size = (10, 3))
d

array([[1, 5, 1],
       [5, 1, 4],
       [3, 4, 5],
       [5, 6, 1],
       [1, 6, 1],
       [4, 6, 1],
       [3, 1, 2],
       [5, 2, 4],
       [4, 1, 4],
       [1, 2, 1]])

In [8]:
avgs = []
for i in range(10):
	roll = 1 + np.random.choice(6, size = (10, 3))
	avgs.append(np.mean(roll))

avgs

[3.8,
 3.7,
 4.033333333333333,
 3.8333333333333335,
 3.6333333333333333,
 3.1666666666666665,
 3.2333333333333334,
 3.433333333333333,
 3.933333333333333,
 3.9]

In [9]:
avgs = []
for i in range(10):
	roll = 1 + np.random.choice(6, size = (3))
	avgs.append(np.mean(roll))

avgs

[5.333333333333333,
 3.0,
 2.6666666666666665,
 3.3333333333333335,
 3.0,
 2.6666666666666665,
 2.6666666666666665,
 4.0,
 2.0,
 4.0]

In [10]:
d = 1 + np.random.choice(6, size = (10, 3))
np.mean(d, axis=1)

array([3.        , 4.        , 3.66666667, 3.        , 2.        ,
       3.33333333, 4.        , 4.33333333, 4.33333333, 3.        ])

In [11]:
R = 10
six = []
for i in range(R):
	d = 1 + np.random.choice(6, size = 2)
	s = np.any(d == 6) + 0
	six.append(s)
six

[0, 0, 1, 1, 0, 0, 1, 1, 0, 1]

In [12]:
R = 10
six = []
for i in range(R):
	d = 1 + np.random.choice(6, size = 2)
	s = np.any(d == 6) + 0
	six.append(s)
np.mean(six)

0.1